### ISSUE TITLE
more adequate defaults for "copy_directories"

### ISSUE THREAD

**Issue by teto** [nvim-neorocks/luarocks-tag-release#15]
when installing a plugin through luarocks it by default only installs the content of the folder "lua" which is a bad default for neovim.

One can add other folders in the action via this snippet:
```
copy_directories: |
            doc
```
`:h runtimepath` lists several folders that we would want to install along with the lua folder:
```

	  filetype.lua	filetypes |new-filetype|
	  autoload/	automatically loaded scripts |autoload-functions|
	  colors/	color scheme files |:colorscheme|
	  compiler/	compiler files |:compiler|
	  doc/		documentation |write-local-help|
	  ftplugin/	filetype plugins |write-filetype-plugin|
	  indent/	indent scripts |indent-expression|
	  keymap/	key mapping files |mbyte-keymap|
	  lang/		menu translations |:menutrans|
	  lua/		|Lua| plugins
	  menu.vim	GUI menus |menu.vim|
	  pack/		packages |:packadd|
	  parser/	|treesitter| syntax parsers
	  plugin/	plugin scripts |write-plugin|
	  query/	|treesitter| queries
	  rplugin/	|remote-plugin| scripts
	  spell/	spell checking files |spell|
	  syntax/	syntax files |mysyntaxfile|
	  tutor/	tutorial files |:Tutor|
```
which is quite cumbersome for everyone to repeat so I would propose to make this list a default ? (maybe without tutor/ lua/ ?)

**Comment by mrcjkb** [comment]
That's a great idea!

The script could search for the default directories in the repo after checkout and then add them if they exist.

Technically, this would be a breaking change, but one could override this by explicitly setting `copy_directories`.
