### ISSUE TITLE
provide a --verbose option ?

### ISSUE THREAD

**Issue by teto** [nvim-neorocks/luarocks-tag-release#20]
To help debug luarocks errors, it would be nice if one could append --verbose to luarocks calls to help troubleshoot errors like https://github.com/teto/nvim-treesitter/actions/runs/4264617755/jobs/7422930329#step:3:348

NB: btw I have an idea of why that doesn't work, I actually already had that error

**Comment by mrcjkb** [comment]
It might be a good idea to have this set by default (or enabled with an environment variable).
There might be a GitHub actions variable for debug logging we could reuse.
