### ISSUE TITLE
CD: Automatic marketplace release on tag push to master

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/luarocks-tag-release#21]
* Tags that match v\*.\*.\*
* Fail if there is no section in changelog

**Comment by teto** [comment]
I seem to be able to use any git ref branch/tag) from this repo without playing with the marketplace ? Would it just advertise the latest tag ?

**Comment by mrcjkb** [comment]
> I seem to be able to use any git ref branch/tag) from this repo without playing with the marketplace ? Would it just advertise the latest tag ?

The marketplace page displays the most recent GitHub release. It's often the first place people find when looking for Github actions.
