### ISSUE TITLE
Tag according to GitHub's recommendation

### ISSUE THREAD

**Issue by MunifTanjim** [nvim-neorocks/luarocks-tag-release#24]
Ref: https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions

> We recommend creating releases using semantically versioned tags – for example, v1.1.3 – and keeping major (v1) and minor (v1.1) tags current to the latest appropriate commit. For more information, see "[About custom actions](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions)" and "[About semantic versioning](https://docs.npmjs.com/about-semantic-versioning).

Example: https://github.com/MunifTanjim/luver-action/tags

**Comment by mrcjkb** [comment]
It looks like the actions-tagger workflow only maintaines a `vX` tag, not a `vX.X` tag.
This is according to [this versioning recommendation](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#versioning).

I think maintaining `vX.X` tags is overkill, so I won't put anymore work into it until the need for it comes up.
