### ISSUE TITLE
How to publish rolling release with `dev` as version

### ISSUE THREAD

**Issue by MunifTanjim** [nvim-neorocks/luarocks-tag-release#25]
Example:
<img width="119" alt="image" src="https://user-images.githubusercontent.com/8050659/221926388-3f948d0a-c480-48cd-804b-0063d1802a26.png">

**Comment by mrcjkb** [comment]
For rolling releases in general, I would recommend looking at [the workflow used by fzf-lua](https://github.com/ibhagwan/fzf-lua/blob/main/.github/workflows/luarocks-release.yaml).

Regarding `dev` versions:
* Luarocks will publish a `dev` version if the `modrev` version in the rockspec is `scm` (e.g. `version = scm-1`).
* I haven't tested this workflow with `scm` releases, but in theory it could work if you set the `template` input to `<package_name>-scm-1.rockspec` (assuming the file exists in your repository). I don't know off the top of my head if the existing `dev` version has to be deleted before a new one is published though.
* One thing to consider is that Luarocks will refuse to install `dev` packages by default, unless explicitly told to do so.
