### ISSUE TITLE
Solution needed for multiple sources of truth due to scm rockspec

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/luarocks-tag-release#33]
For nixpkgs to be able to detect plugins on luarocks, there needs to be a rockspec in the repository (@teto please correct me if I am wrong about this).

Maintaining an scm rockspec adds a source of truth and can be error-prone - especially if plugin authors are not familiar with the rockspec format.
For example, I have come across neovim plugins with rockspecs that have outdated `copy_directories` fields.

A potential solution could be for this workflow to add a step that opens a PR with an updated scm rockspec, if it has changed.

**Comment by teto** [comment]
the updater script loops over https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/luarocks-packages.csv : 
if there is no source it looks for the package name on luarocks.org and it will fetch it from there =>  it doesn't need a rockspec in the git repo.
If you set "src" in the above csv file, it will look for a rockspec in the repo and if the heuristic fails, you can specify one.

**Comment by mrcjkb** [comment]
Thanks for the info.
