### ISSUE TITLE
v5.4.0 breaks my plugin's tests

### ISSUE THREAD

**Issue by carbon-steel** [nvim-neorocks/luarocks-tag-release#332]
I noticed my Neovim plugin's tests were failing for a PRs (even no-ops). I found that pinning luacks-tag-release to v5.3.14 made the failures stop.

Here is an example of a passing test (v5.3.14): https://github.com/carbon-steel/detour.nvim/actions/runs/7824257802/job/21346534527

Here is an example of a failing test (v5.4.0): https://github.com/carbon-steel/detour.nvim/actions/runs/7824302847/job/21346652999?pr=54

The key error seems to be that `vim` is a `nil` value in v5.4.0:

> lua/detour/movements.lua:8: attempt to index global 'vim' (a nil value)

The file above is not even a test file. It's a regular code file of my plugin. To be clear, my plugin is working fine and the tests are passing when I run them locally.

**Comment by mrcjkb** [comment]
Hey :wave: 

Thanks for reporting :pray: 
Strange, all that update did was get rid of the nix output.
Maybe it's one of the dependency updates.
