### ISSUE TITLE
`neolua` -> `nlua`

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/luarocks-tag-release#430]
Related to `neorocks` itself but applicable here, feel free to let me know if I should transfer it over there.

Regular users are likely to bundle their projects with `nlua` as a test dependency and specify that as their Lua interpreter in their `.busted` file.

This causes tests run by `luarocks-tag-release` to fail, since it'll try to execute a nonexistent `nlua` binary. This should be fixable by making `neorocks` use `nlua` as the binary name instead of `neolua`.

**Comment by mrcjkb** [comment]
I'm wondering if it's best to just disable/deprecate running tests in favour of https://github.com/nvim-neorocks/nvim-busted-action, which can be chained with this one.

**Comment by vhyrro** [comment]
I think separating the two is a good call. Let this CI focus solely on luarocks releases, and let the busted action do the testing :)

**Comment by mikavilpas** [comment]
In my case my test suite has dependencies to an external application being installed on the system. Would be great to leave testing out of the release step. 🙂
