### ISSUE TITLE
ENOENT when trying to upload a release

### ISSUE THREAD

**Issue by Julian** [nvim-neorocks/luarocks-tag-release#456]
Hi there.

This seems like it might be a luarocks issue rather than one specific to this plugin, but I'm not sure how to diagnose, so feel free to close if so.

I set up this action to try out on [lean.nvim](https://github.com/Julian/lean.nvim) by creating a [rockspec similar to the one I see in the README and in other plugins](https://github.com/Julian/lean.nvim/blob/main/lean.nvim-scm-1.rockspec) but when running the action I get:

```
stderr: cp: cannot stat '/home/runner/work/_temp/tmp.5LkalSa1LK/lib/luarocks/rocks-5.1/lean.nvim/1.0.0-1/lua/tests/fixtures/example-project/foo/lean-toolchain': No such file or directory

Error: Failed copying /home/runner/work/_temp/tmp.5LkalSa1LK/lib/luarocks/rocks-5.1/lean.nvim/1.0.0-1/lua/tests/fixtures/example-project/foo/lean-toolchain to /home/runner/work/_temp/tmp.5LkalSa1LK/share/lua/5.1/tests/fixtures/example-project/foo/lean-toolchain

stack traceback:
	[C]: in function 'on_failure'
	...-luarocks-tag-release-scm-1/share/lua/5.1/ltr/os.lua:48: in function 'execute'
	...release-scm-1/share/lua/5.1/luarocks-tag-release.lua:62: in function 'create_rockspec'
	...release-scm-1/share/lua/5.1/luarocks-tag-release.lua:145: in function 'luarocks_tag_release'
	...ag-release/scm-1/bin/luarocks-tag-release-action.lua:83: in main chunk
	[C]: ?
Workflow has been triggered by: tag
```

Sample full run [here](https://github.com/Julian/lean.nvim/actions/runs/9828063092/job/27131490540#step:3:484) though obviously GH Actions will purge it eventually.

**Comment by mrcjkb** [comment]
Hey :wave: 

This does seem to be a luarocks issue. When creating the rockspec, before uploading, the action runs `luarocks install <generated-rockspec>` to verify that it can be used.

The install is failing because luarocks seems to be having issues with the `lua/tests/fixtures/example-project/foo/lean-toolchain` file.

To debug, you could copy the generated rockspec and paste it into a `lean.nvim-scm-1.rockspec` (change the version to `scm`).
Then you can troubleshoot with `luarocks make lean.nvim-scm-1.rockspec --tree /tmp/debug`.

**Comment by Julian** [comment]
Thanks for the info! Will give that a shot, appreciated!

**Comment by Julian** [comment]
Well, that (`luarocks make`) definitely helped reproduce the error, but I have no idea what causes it / how to fix it -- from what I can tell, indeed the `lua/` folder isn't copied over, and that file indeed doesn't exist in the `/tmp/debug` tree, but I don't see any neovim plugins seeming to put `lua/` in their `copy_directories` -- the file definitely exists in the source tree (and is tracked by git in case that matters). Will put this on ice until I have some more time to learn about Lua's build tooling I guess, but appreciate the hint (and would definitely not mind a second one if you have a moment, but certainly not expecting anything).

**Comment by mrcjkb** [comment]
`lua` is a special source directory, that doesn't need to be specified in `copy_directories`.
The same applies to some directories like `lib`, `tests`, `doc`, `docs`.

Perhaps luarocks is somehow getting confused by the `lua/tests` subdirectory?
Normally, a Lua package has either a `spec` or `test` or `tests` directory in the root.

**Comment by Julian** [comment]
Huh, that does seem to fix it.
I honestly haven't seen neovim plugins do things that way, even ones with rockspecs (though I bet not many are uploading to luarocks?) -- but all the ones I've seen have `lua/tests`, but I'll confess I haven't stayed up to date nor certainly looked around too hard, so I do trust you're right in the broader Lua ecosystem.
Thanks for the tips!

**Comment by mrcjkb** [comment]
It probably depends on the test framework you're using. busted and plenary.nvim (which has a legacy test framework that is based on busted) both default to a `spec` or `test` directory in the root directory.
