### ISSUE TITLE
Fails to run luarocks test with test_interpreter lua and a luarocks template

### ISSUE THREAD

**Issue by ncopa** [nvim-neorocks/luarocks-tag-release#75]
I have a very simple single file lua module, [lua-optarg](https://github.com/ncopa/lua-optarg), which I am trying to set up to use luarocks-tag-release, using a `luarocks.template`. But it seems like luarocks test is executed before the template is generated, so it ends up with error when running luarock test with `pull_request`.

The error I get is:
```
Run luarocks-tag-release-action
  luarocks-tag-release-action
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    LUAROCKS_API_KEY: ***
    INPUT_NAME: optarg
    INPUT_VERSION: 9/merge
    INPUT_DEPENDENCIES: lua >= 5.1
  
    INPUT_LABELS: 
    INPUT_COPY_DIRECTORIES: 
    INPUT_SUMMARY: 
    INPUT_DETAILED_DESCRIPTION: 
    INPUT_TEMPLATE: ./rockspec.template
    INPUT_LICENSE: 
    INPUT_TEST_INTERPRETERS: lua
  
/nix/store/n26kll9i31a36x5nn511xp7za3gcwpx8-luajit-2.1.0-2022-10-04/bin/luajit: ...tag-release-scm-1/share/lua/5.1/luarocks-tag-release.lua:80: FAILED (exit code 256): luarocks test No existing manifest. Attempting to rebuild...
Workflow has been triggered by: branch
Publishing an untagged release.
Running in a pull request.
Using template: ./rockspec.template
Generating Luarocks release 0.0.0 for: optarg version 0.0.0 from ref 519db036f590f23a1ee45543af63bf2b9af4ee99.

Generated rockspec:
========================================================================================
-- vim: set ft=lua:
local git_ref = '519db036f590f23a1ee45543af63bf2b9af4ee99'
local modrev = '0.0.0'
local specrev = '1'

local repo_url = 'https://github.com/ncopa/lua-optarg'

rockspec_format = '3.0'
package = 'optarg'
version = modrev ..'-'.. specrev

description = {
  summary = 'Simple command line option parser',
  detailed = '',
  labels = { },
  homepage = 'https://github.com/ncopa/lua-optarg',
  license = 'MIT'
}

dependencies = { 'lua >= 5.1', 'lua >= 5.1' } 

source = {
  url = repo_url .. '/archive/' .. git_ref .. '.zip',
  dir = 'lua-optarg-' .. '519db036f590f23a1ee45543af63bf2b9af4ee99',
}

build = {
  type = 'builtin',
  modules = {
    optarg = 'optarg.lua'
  }
}

========================================================================================
Initialising luarocks project...
Done.
Configuring luarocks to use interpreter lua...
Done.
Running tests...

Error: test suite failed.

stack traceback:
	[C]: in function 'on_failure'
	...tag-release-scm-1/share/lua/5.1/luarocks-tag-release.lua:80: in function 'execute'
	...tag-release-scm-1/share/lua/5.1/luarocks-tag-release.lua:95: in function 'luarocks_test'
	...tag-release-scm-1/share/lua/5.1/luarocks-tag-release.lua:241: in function 'luarocks_tag_release'
	...ks-tag-release/scm-1/bin/luarocks-tag-release-action.lua:151: in main chunk
	[C]: at 0x004062c0
Error: Process completed with exit code 1.
```
Full log: https://github.com/ncopa/lua-optarg/actions/runs/5682576662/job/15401258782?pr=9

Looking at the example configuration from wiki, https://github.com/nvim-lua/plenary.nvim/blob/master/.github/workflows/release.yml, I notice that they have both a [plenary.nvim-scm-1.rockspec](https://github.com/nvim-lua/plenary.nvim/blob/267282a9ce242bbb0c5dc31445b6d353bed978bb/plenary.nvim-scm-1.rockspec) and a [rockspec.template](https://github.com/nvim-lua/plenary.nvim/blob/267282a9ce242bbb0c5dc31445b6d353bed978bb/rockspec.template), which make me think that either they are not using the template at all or the github action is not testing the generated template on github `pull_request`.

**Comment by mrcjkb** [comment]
Hi. Thanks for reporting this.
I'm on vacation until August 2nd, so I won't be able to debug this myself until then.

plenary.nvim are using an older version of luarocks-tag-release, which doesn't run luarocks test at all.

Based on the full log you posted, `luarocks test` is being run after the rockspec was generated.

The log can be confusing, because GitHub actions prints the error message that caused the failure first, and then the output of the luarocks-tag-release script.

I'm not sure yet what the `No existing manifest` error means...

**Comment by mrcjkb** [comment]
One thing I noticed (not sure if that is causing problems in your workflow) is that the generated rockspec has two `lua >= 5.1` dependencies (caused by #76).

For now, you can just remove the `dependencies` input from the workflow yaml.

**Comment by mrcjkb** [comment]
Here's the `.busted` file we use in our own CI: https://github.com/nvim-neorocks/luarocks-tag-release/blob/master/.busted

IIRC, I had to disable coverage for it to work.

**Comment by ncopa** [comment]
> I'm on vacation

Enjoy your vacation!

**Comment by ncopa** [comment]
I tried to reproduce this locally by:
- copy contents of the rockspec file (from error output) into a local `optarg-0.0.0-1`
- run the steps in `luarocks_test`:
  - `luarocks-5.1 init`
  - `luarocks-5.1 config --scope project lua_interpreter lua` 
  - `luarocks-5.1 test`
 
But I was not able to reproduce the issue. It works here. I noticed that I have a slightly newer version of luarocks, 3.9.2.

```console
ncopa-desktop:~/Projects/lua-optarg (luarocks-release)$ luarocks-5.1 init

Initializing project 'lua-optarg' for Lua 5.1 ...
-------------------------------------------------

Checking your Lua installation ...
Adding entries to .gitignore ...
Preparing ./.luarocks/ ...
Wrote .luarocks/config-5.1.lua
Preparing ./lua_modules/ ...
Preparing ./luarocks ...
Preparing ./lua for version 5.1...
ncopa-desktop:~/Projects/lua-optarg (luarocks-release)$ luarocks-5.1 config --scope project lua_interpreter lua
Wrote
	lua_interpreter = "lua"
to
	./.luarocks/config-5.1.lua
ncopa-desktop:~/Projects/lua-optarg (luarocks-release)$ luarocks-5.1 test

optarg 0.0.0-1 depends on lua >= 5.1 (5.1-1 provided by VM)
●●●●●●●●●●●●●●●●●●●●●●●●●●
26 successes / 0 failures / 0 errors / 0 pending : 0.00517 seconds
ncopa-desktop:~/Projects/lua-optarg (luarocks-release)$ luarocks-5.1 --version
/usr/bin/luarocks-5.1 3.9.2
LuaRocks main command-line interface
```

**Comment by mrcjkb** [comment]
I've just released a new patch so that the script will print both stdout and stderr on failure (it was only printing stderr before).
Maybe that'll help us figure out why it's failing.

**Comment by ncopa** [comment]
Thank you! yes, that did explain what happened. I never set the `package.path` so the local `./optarg.lua` was never found by busted.

Thank you!
